/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as sideBettingSol from "./SideBetting.sol";
export { BattleFactory__factory } from "./BattleFactory__factory";
export { Faucet__factory } from "./Faucet__factory";
