/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sideBettingSol from "./SideBetting.sol";
export type { sideBettingSol };
export type { BattleFactory } from "./BattleFactory";
export type { Faucet } from "./Faucet";
export * as factories from "./factories";
export { BattleFactory__factory } from "./factories/BattleFactory__factory";
export { Faucet__factory } from "./factories/Faucet__factory";
export type { IFaucet } from "./SideBetting.sol/IFaucet";
export { IFaucet__factory } from "./factories/SideBetting.sol/IFaucet__factory";
export type { SideBetting } from "./SideBetting.sol/SideBetting";
export { SideBetting__factory } from "./factories/SideBetting.sol/SideBetting__factory";
