/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IFaucet, IFaucetInterface } from "../../SideBetting.sol/IFaucet";

const _abi = [
  {
    inputs: [],
    name: "getGameResult",
    outputs: [
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGameStatus",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlayers",
    outputs: [
      {
        internalType: "address",
        name: "player1",
        type: "address",
      },
      {
        internalType: "address",
        name: "player2",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFaucet__factory {
  static readonly abi = _abi;
  static createInterface(): IFaucetInterface {
    return new Interface(_abi) as IFaucetInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFaucet {
    return new Contract(address, _abi, runner) as unknown as IFaucet;
  }
}
