/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFaucet__factory } from "./IFaucet__factory";
export { SideBetting__factory } from "./SideBetting__factory";
